from enum import Enum
import pygame

# WINDOW PARAMETERS

# DRAWING POSITIONS
HEALTH_BAR_WIDTH = 300
HEALTH_BAR_HEIGHT = 5
STATUS_BAR_HEIGHT = 0

UPGRADE_BAR_TOP = 60
UPGRADE_BAR_LEFT = 10
UPGRADE_BAR_SPACING = 80
UPGRADE_ICON_SIZE = 40
# FPS
FPS = 60

class GameState(Enum):
    DEBUG, START_SCREEN, GAME_OVER, RUNNING, PAUSED, UPGRADE, QUIT, PAUSE = range(8)


SHIELD_INITIAL_DAMAGE = 20
BG_SPEED = 0.5

# Events

NEXT_LEVEL_EVENT = pygame.USEREVENT + 1
SPACESHIP_DESTROYED = pygame.USEREVENT + 2
PLANET_EVENT = pygame.USEREVENT + 3


class EnemySpawnEvent(Enum):
    SWARM = pygame.USEREVENT + 10
    ASTEROID = pygame.USEREVENT + 11
    FIREBALL = pygame.USEREVENT + 12
    SLASHBULLET = pygame.USEREVENT + 13
    SINESHIP = pygame.USEREVENT + 14
    CHASERSHIP = pygame.USEREVENT + 15


ANCHORED_OFFSET_EVENT = pygame.USEREVENT + 100
ABSOLUTE_MOVE_EVENT = pygame.USEREVENT + 101

SIMPLE_BULLET_EVENT = pygame.USEREVENT + 200
TARGETED_ROUND_BULLET_EVENT = pygame.USEREVENT + 201