from enum import Enum
import pygame

# WINDOW PARAMETERS

# DRAWING POSITIONS
HEALTH_BAR_WIDTH = 300
HEALTH_BAR_HEIGHT = 5
STATUS_BAR_HEIGHT = 0

# FPS
FPS = 60

class GameState(Enum):
    TEST, START_SCREEN, GAME_OVER, RUNNING, PAUSED, UPGRADE, QUIT = range(7)


SHIELD_INITIAL_DAMAGE = 20
BG_SPEED = 0.5

# Events

NEXT_LEVEL_EVENT = pygame.USEREVENT + 1
SPACESHIP_DESTROYED = pygame.USEREVENT + 2
PLANET_EVENT = pygame.USEREVENT + 3


class EnemySpawnEvent(Enum):
    SWARM = pygame.USEREVENT + 10
    ASTEROID = pygame.USEREVENT + 11
    FIREBALL = pygame.USEREVENT + 12
    SLASHBULLET = pygame.USEREVENT + 13
    SINESHIP = pygame.USEREVENT + 14


ANCHORED_OFFSET_EVENT = pygame.USEREVENT + 100
